meta_product_name: "Tinpet"
meta_title: "Tinpet - Rencontre les amoureux du meilleur ami de l'Homme"
meta_description: "Sur Tinpet tu peux non seulement rencontrer des passionnés d'animaux comme toi mais aussi offrir une vie sociale à ton chien"
meta_image: "photo-meta.png" # should exist in `app/assets/images/`
